/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.filme;

import controller.FilmeController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author marcus.rodrigues
 */
public class FilmePainelFormulario extends javax.swing.JPanel {

    private FilmeController filmeController;    
    private JLabel labelPainelFormulario;
    
    public FilmePainelFormulario() {
        initComponents();
    }
    
    public FilmePainelFormulario(FilmeController filmeController) {
        this.filmeController = filmeController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelcodFilme = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelSinopse = new javax.swing.JLabel();
        jLabelDtInicial = new javax.swing.JLabel();
        jTextFieldCodFilme = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldSinopse = new javax.swing.JTextField();
        jTextFieldDtInicial = new javax.swing.JTextField();
        jButtonCadastra = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelDtFinal = new javax.swing.JLabel();
        jTextFieldDtFinal = new javax.swing.JTextField();

        jLabelcodFilme.setText("Cód. Filme:");

        jLabelTitulo.setText("Titulo:");

        jLabelGenero.setText("Genero:");

        jLabelSinopse.setText("Sinopse:");

        jLabelDtInicial.setText("Data Inicial:");

        jButtonCadastra.setText("Cadastra");
        jButtonCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelDtFinal.setText("Data Final:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelcodFilme)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelGenero)
                            .addComponent(jLabelSinopse)
                            .addComponent(jLabelDtInicial)
                            .addComponent(jLabelDtFinal))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(jTextFieldCodFilme)
                            .addComponent(jTextFieldGenero)
                            .addComponent(jTextFieldSinopse)
                            .addComponent(jTextFieldDtInicial)
                            .addComponent(jTextFieldDtFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcodFilme)
                    .addComponent(jTextFieldCodFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenero)
                    .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSinopse)
                    .addComponent(jTextFieldSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDtInicial)
                    .addComponent(jTextFieldDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDtFinal)
                    .addComponent(jTextFieldDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastra)
                    .addComponent(jButtonVoltar)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraActionPerformed
        // TODO add your handling code here:
        filmeController.salvarFilme(this.jTextFieldCodFilme.getText(),
                                    this.jTextFieldTitulo.getText(), 
                                    this.jTextFieldGenero.getText(), 
                                    this.jTextFieldSinopse.getText(), 
                                    this.jTextFieldDtInicial.getText(), 
                                    this.jTextFieldDtFinal.getText());
    }//GEN-LAST:event_jButtonCadastraActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        filmeController.voltarPrincipal();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    public JButton getjButtonCadastra() {
        return jButtonCadastra;
    }

    public JButton getjButtonVoltar() {
        return jButtonVoltar;
    }

    public JTextField getjTextFieldCodFilme() {
        return jTextFieldCodFilme;
    }

    public JTextField getjTextFieldDtFinal() {
        return jTextFieldDtFinal;
    }

    public JTextField getjTextFieldDtInicial() {
        return jTextFieldDtInicial;
    }

    public JTextField getjTextFieldGenero() {
        return jTextFieldGenero;
    }

    public JTextField getjTextFieldSinopse() {
        return jTextFieldSinopse;
    }

    public JTextField getjTextFieldTitulo() {
        return jTextFieldTitulo;
    }

    public JLabel getLabelPainelFormulario() {
        return labelPainelFormulario;
    }

    
    public void zerarCampos(){
            this.jTextFieldCodFilme.setText("");
            this.jTextFieldTitulo.setText("");
            this.jTextFieldGenero.setText("");
            this.jTextFieldSinopse.setText("");
            this.jTextFieldDtInicial.setText("");
            this.jTextFieldDtFinal.setText("");
        }
        public void carregaDados(String codFilme, String titulo, String genero, String sinopse, String dataInicio, String dataFinal) {
            this.jTextFieldCodFilme.setText(codFilme);
            this.jTextFieldTitulo.setText(titulo);
            this.jTextFieldGenero.setText(genero);
            this.jTextFieldSinopse.setText(sinopse);
            this.jTextFieldDtInicial.setText(dataInicio);
            this.jTextFieldDtFinal.setText(dataFinal);
        }
        public void habilitaEdicaoFormFilme(boolean valor) {
            this.jTextFieldCodFilme.setEditable(valor);
            this.jTextFieldTitulo.setEditable(valor);
            this.jTextFieldGenero.setEditable(valor);
            this.jTextFieldSinopse.setEditable(valor);
            this.jTextFieldDtInicial.setEditable(valor);
            this.jTextFieldDtFinal.setEditable(valor);
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastra;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelDtFinal;
    private javax.swing.JLabel jLabelDtInicial;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelSinopse;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelcodFilme;
    private javax.swing.JTextField jTextFieldCodFilme;
    private javax.swing.JTextField jTextFieldDtFinal;
    private javax.swing.JTextField jTextFieldDtInicial;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldSinopse;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
