/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sala;

import controller.SalaController;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author marcus.rodrigues
 */
public class SalaPainelFormulario extends javax.swing.JPanel {

    private SalaController salaController;
    private SalaPainelFormulario salaPainelFormulario;
    
    /**
     * Creates new form SalaPainelFormulario
     */
    public SalaPainelFormulario() {
        initComponents();
    }

     public SalaPainelFormulario(SalaController salaController) {
        this.salaController = salaController;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumero = new javax.swing.JLabel();
        jLabelQtdCadeiras = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldQtdCadeiras = new javax.swing.JTextField();
        jButtonCadastra = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        jLabelNumero.setText("Numero:");

        jLabelQtdCadeiras.setText("Qtd. Cadeiras:");

        jButtonCadastra.setText("Cadastra");

        jButtonVoltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQtdCadeiras)
                    .addComponent(jLabelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jTextFieldQtdCadeiras))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonCadastra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQtdCadeiras)
                    .addComponent(jTextFieldQtdCadeiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastra)
                    .addComponent(jButtonVoltar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonCadastra() {
        return jButtonCadastra;
    }

    public JButton getjButtonVoltar() {
        return jButtonVoltar;
    }

    public JTextField getjTextFieldNumero() {
        return jTextFieldNumero;
    }

    public JTextField getjTextFieldQtdCadeiras() {
        return jTextFieldQtdCadeiras;
    }

    public SalaPainelFormulario getSalaPainelFormulario() {
        return salaPainelFormulario;
    }
    

     public void zerarCampos(){
         this.jTextFieldNumero.setText("");
         this.jTextFieldQtdCadeiras.setText("");
        }
        public void carregaDados(String numero, String qtdCadeiras) {
            this.jTextFieldNumero.setText(numero);
            this.jTextFieldQtdCadeiras.setText(qtdCadeiras);
        }
        public void habilitaEdicaoFormSala(boolean valor) {
            this.jTextFieldNumero.setEditable(valor);
            this.jTextFieldQtdCadeiras.setEditable(valor);
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastra;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelQtdCadeiras;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldQtdCadeiras;
    // End of variables declaration//GEN-END:variables
}
